# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: MIT

name: Release

on:
  push:
    tags:
    - '*'

jobs:
  create_release:
    runs-on: ubuntu-24.04
    name: Create release on GitHub
    permissions:
      contents: write
    steps:
    - uses: ncipollo/release-action@1c89adf39833729d8f85a31ccbc451b078733c80 # v1.19.1
      with:
        generateReleaseNotes: true
permissions:
  contents: read
