# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: MIT

name: Release

on:
  push:
    tags:
    - '*'

jobs:
  create_release:
    runs-on: ubuntu-24.04
    name: Create release on GitHub
    permissions:
      contents: write
    steps:
    - uses: ncipollo/release-action@98d25d4189e9b6cee19b8635b1ea5cc39c158a41 # v1.19.2
      with:
        generateReleaseNotes: true
permissions:
  contents: read
